language: python

python:
  - "2.6"
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip install coverage

script:
  - if [[ $TRAVIS_PYTHON_VERSION < 3 ]]; then cd aliyun-python-sdk-core; else cd aliyun-python-sdk-core-v3; fi
  - coverage run --branch -m pytest tests/

notifications:
    webhooks: https://oapi.dingtalk.com/robot/send?access_token=096ed387df243a6d60835aadeccc47165f3813bc7cb81cdd0cfeadfd28e3acc1
    email: false
    on_success: change
    on_failure: always

after_success:
  - bash <(curl -s https://codecov.io/bash)
